### ISSUE TITLE
Setting environment variables for docker-composer

### ISSUE THREAD

**Issue by jefoy** [odoo/odoo#100329]
Impacted versions: 15.0

Steps to reproduce:

I'm trying to set environment variables for my dockered odoo.
But, after `docker-compose up -d` I can see this in log files:
`Database connection failure: invalid integer value "$DB_PORT" for connection option "port"`

Seems container does not accept such implementation of variables.
But, how to make it works?

Here is my odoo.conf, odoo_variables.env and docker-compose.yml:

**odoo.conf**

```
[options]

; *** This volumes are mounted from the Docker host ***
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo

; *** Basic config ***
admin_passwd = $MASTER_PASS
db_host = $DB_HOST
db_port = $DB_PORT
db_user = $DB_USER
db_password = $DB_PASS
dbfilter = ^$DB_FILTER.*$
db_maxconn = 64

; *** SMTP and email config ***
smtp_server = $SMTP_SERVER
smtp_port = $SMTP_PORT
smtp_user = $SMTP_USER
smtp_password = $SMTP_PASS
MAYBE you have to use this port:
smtp_ssl = True
email_from = False
```

**odoo_variables.env**

```
MASTER_PASS=P@ssw0rd-m@ster
DB_HOST=192.168.33.12
DB_PORT=5432
DB_USER=odoo_db_adm
DB_PASS=Pa$$w0rd-db
DB_FILTER=odoo_test_db_
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=465
SMTP_USER=test@gmail.com
SMTP_PASS=Sup3rP@$$w0dr!
```

**docker-compose.yml**

```
version: '3.1'
services:
  web:
    image: odoo:15.0
    ports:
      - "8069:8069"
    volumes:
      - /mnt/odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra_addons:/mnt/extra-addons
    env_file:
      - /run/secrets/odoo_variables.env
```

Current behavior: Database connection failure: invalid integer value "$DB_PORT" for connection option "port

Expected behavior: Running instance
