### ISSUE TITLE
`proxy_mode = True` no honoured at all

### ISSUE THREAD

**Issue by troykelly** [odoo/odoo#104947]
Impacted versions: Odoo 16.0-20221025 (Community Edition)

Steps to reproduce:
1. Create docker environment using `odoo:latest`
2. Start environment
3. Configure with `proxy_mode = True`

Current behavior: All headers are ignored, internal docker IP's are used

Expected behavior: Per documentation, the correct remote IP should appear in logs

Video/Screenshot link (optional):

Traefik log

```text
sy3-cluster-abc-traefik_traefik.0.pwozanbg702m@cluster-c    | 2404:79c0:1002:300:ad5e:979b:1616:909e - - [03/Nov/2022:23:55:59 +0000] "GET /web/image/res.company/1/favicon HTTP/2.0" 304 0 "-" "-" 272 "odoo-production-https@docker" "http://10.0.1.94:8069" 26ms
```

Access log
```yaml
---
ClientAddr: 172.68.146.10:23374
ClientHost: 2404:79c0:1002:300:ad5e:979b:1616:909e
ClientPort: '23374'
ClientUsername: "-"
DownstreamContentSize: 0
DownstreamStatus: 304
Duration: 22557103
OriginContentSize: 0
OriginDuration: 22479960
OriginStatus: 304
Overhead: 77143
RequestAddr: crm.aperim.au
RequestContentSize: 0
RequestCount: 84
RequestHost: crm.aperim.au
RequestMethod: GET
RequestPath: "/web/image/res.company/1/favicon"
RequestPort: "-"
RequestProtocol: HTTP/2.0
RequestScheme: https
RetryAttempts: 0
RouterName: odoo-production-https@docker
ServiceAddr: 10.0.1.94:8069
ServiceName: odoo-production@docker
ServiceURL:
  Scheme: http
  Opaque: ''
  User:
  Host: 10.0.1.94:8069
  Path: ''
  RawPath: ''
  OmitHost: false
  ForceQuery: false
  RawQuery: ''
  Fragment: ''
  RawFragment: ''
StartLocal: '2022-11-04T00:47:02.573482376Z'
StartUTC: '2022-11-04T00:47:02.573482376Z'
TLSCipher: TLS_AES_128_GCM_SHA256
TLSVersion: '1.3'
downstream_Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
downstream_Cache-Control: no-cache
downstream_Content-Disposition: inline; filename=Aperim
downstream_Content-Security-Policy: default-src 'none'
downstream_Date: Fri, 04 Nov 2022 00:47:02 GMT
downstream_Etag: '"2f7028932480cdcb927f83b0165d577669e620fa-0x0-crop=False-quality=0"'
downstream_Server: Werkzeug/1.0.1 Python/3.9.2
downstream_X-Content-Type-Options: nosniff
entryPointName: http3
level: info
msg: ''
origin_Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
origin_Cache-Control: no-cache
origin_Content-Disposition: inline; filename=Aperim
origin_Content-Security-Policy: default-src 'none'
origin_Date: Fri, 04 Nov 2022 00:47:02 GMT
origin_Etag: '"2f7028932480cdcb927f83b0165d577669e620fa-0x0-crop=False-quality=0"'
origin_Server: Werkzeug/1.0.1 Python/3.9.2
origin_X-Content-Type-Options: nosniff
request_Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
request_Accept-Encoding: gzip
request_Accept-Language: en-AU,en-GB;q=0.9,en-US;q=0.8,en;q=0.7
request_Cdn-Loop: cloudflare
request_Cf-Connecting-Ip: 2404:79c0:1002:300:ad5e:979b:1616:909e
request_Cf-Ipcountry: AU
request_Cf-Ray: 764955f01875a835-SYD
request_Cf-Visitor: '{"scheme":"https"}'
request_Cookie: cids=1; session_id=1dc6ba06d4a7ac07e65eb63c590ea2d1ced0e573; im_livechat_history=["/"];
  frontend_lang=en_AU; tz=Australia/Sydney
request_If-Modified-Since: Thu, 03 Nov 2022 06:21:47 GMT
request_If-None-Match: W/"2f7028932480cdcb927f83b0165d577669e620fa-0x0-crop=False-quality=0"
request_Priority: u=1
request_Referer: https://crm.aperim.au/web
request_Sec-Ch-Ua: '"Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"'
request_Sec-Ch-Ua-Mobile: "?0"
request_Sec-Ch-Ua-Platform: '"macOS"'
request_Sec-Fetch-Dest: image
request_Sec-Fetch-Mode: no-cors
request_Sec-Fetch-Site: same-origin
request_User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
  (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
request_X-Forwarded-For: 2404:79c0:1002:300:ad5e:979b:1616:909e
request_X-Forwarded-Host: crm.aperim.au
request_X-Forwarded-Port: '443'
request_X-Forwarded-Proto: https
request_X-Forwarded-Server: 7992afddbdf0
request_X-Real-Ip: 2404:79c0:1002:300:ad5e:979b:1616:909e
time: '2022-11-04T00:47:02Z'
```

odoo log
```text
odoo_odoo.1.6zg2kzsaqwxd@cluster-a    | 2022-11-04 00:47:02,223 1 INFO aperim werkzeug: 172.68.146.10 - - [04/Nov/2022 00:47:02] "GET /web/image/res.company/1/favicon HTTP/1.1" 304 - 6 0.005 0.013
```

Support ticket number submitted via odoo.com/help (optional):
