### ISSUE TITLE
Odoo Apps will be available soon

### ISSUE THREAD

**Issue by tesudacochino** [odoo/odoo#113100]
All the versions of odoo that I have tried I get this message when I press update or Apps Store in the apps section in developer mode. is this a bug? An odoo service is down? I can't download updates.

```
Odoo Apps will be available soon
Showing locally available modules
```

Impacted versions:
odoo 16
odoo 15
odoo 14

Steps to reproduce:
Launch docker

```
version: '3.1'
services:
  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
```

Go to Apss section in developer mode
http://localhost:8069/web?debug=assets#action=36&model=ir.module.module&view_type=kanban&cids=1&menu_id=5
Current behavior:
Show this message:
```
Odoo Apps will be available soon
Showing locally available modules
```

Expected behavior:
Update list 

Video/Screenshot link (optional):
![imagen](https://user-images.githubusercontent.com/13074983/220063875-b62012c0-25bf-4fd2-b91e-84bf878965a5.png)
