### ISSUE TITLE
[16.0] Running Odoo 16.0 with Python version 3.11 does not work

### ISSUE THREAD

**Issue by pnajman-modoolar** [odoo/odoo#116282]
**Impacted versions**:  _Odoo 16.0 Python 3.11_
**Steps to reproduce**: _Run Odoo with the official latest Odoo docker image_
**Current behavior**: _Odoo does not work with this setup_

**Expected behavior**: 
_This should work as per following commit from the last week_ [fbe4932](https://github.com/odoo/odoo/commit/fbe4932cd583a2cc019644807a7ea248d34eec80)

**Support ticket number submitted via odoo.com/help**: _#3245278_

**Stack trace**: [odoo-16.0-py-3.11-stack-trace.txt](https://github.com/odoo/odoo/files/11044833/odoo-16.0-py-3.11-stack-trace.txt)

**Comment by d-fence** [comment]
Can you give more information.
`Steps to reproduce: Run Odoo with the official latest Odoo docker image`  is wrong, the latest Odoo docker image provides Python 3.9.2.

So it's difficult to reproduce.

**Comment by icvetkovic-modoolar** [comment]
Steps to reproduce:

1. Clone latest 16.0 branch code
2. Create following Docker file based on official Python 3.11 image:
```
FROM python:3.11.2

# variable postgres client version
RUN apt-get update \
    && apt-get install -qq -y --no-install-recommends \
        software-properties-common ca-certificates wget bash dirmngr fonts-noto-cjk gnupg2 \
        nodejs node-less locales libjpeg-dev libpq-dev libsasl2-dev libldap2-dev \
        libtiff5-dev libopenjp2-7-dev libfreetype6-dev liblcms2-dev libwebp-dev \
        libharfbuzz-dev libfribidi-dev libxcb1-dev gcc build-essential \
        expect tcl8.6 git libxml2-dev libxslt-dev zlib1g-dev postgresql-client fonts-dejavu-core  \
        fonts-freefont-ttf fonts-freefont-otf fonts-noto-core fonts-inconsolata fonts-font-awesome \
        fonts-roboto-unhinted gsfonts libjs-underscore \
    && locale-gen en_US.UTF-8 \
    && dpkg-reconfigure locales \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/project \
    && mkdir -p /opt/odoo/data

WORKDIR /opt/project

# Expose Odoo services
EXPOSE 8069 8071
```
3. Create docker-compose.yml file with following services:
```
version: '3.8'
services:
  odoo:
    build: .
    environment:
      PYTHONBUFFERED: 1
      PGHOST: postgres
      PGUSER: odoo
      PGPASSWORD: odoo
    ports:
      - "8069:8069"
      - "8071:8071"
    command:
      - /bin/bash
      - -c
      - |
        python3 -m pip install -r /opt/project/odoo/requirements.txt  && python3 /opt/project/odoo/odoo-bin
    depends_on:
      - postgres
    volumes:
      - ./odoo:/opt/project/odoo

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - /tmp:/tmp
    restart: unless-stopped

```
4. Run `docker-compose up`

Expected behavior: Odoo service is started

Issue: Odoo service fails with following stack trace:

```
odoo_1      | Traceback (most recent call last):
odoo_1      |   File "/opt/project/odoo/odoo-bin", line 5, in <module>
odoo_1      |     import odoo
odoo_1      |   File "/opt/project/odoo/odoo/__init__.py", line 133, in <module>
odoo_1      |     from . import cli
odoo_1      |   File "/opt/project/odoo/odoo/cli/__init__.py", line 11, in <module>
odoo_1      |     from . import scaffold
odoo_1      |   File "/opt/project/odoo/odoo/cli/scaffold.py", line 9, in <module>
odoo_1      |     import jinja2
odoo_1      |   File "/usr/local/lib/python3.11/site-packages/jinja2/__init__.py", line 12, in <module>
odoo_1      |     from .environment import Environment
odoo_1      |   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 25, in <module>
odoo_1      |     from .defaults import BLOCK_END_STRING
odoo_1      |   File "/usr/local/lib/python3.11/site-packages/jinja2/defaults.py", line 3, in <module>
odoo_1      |     from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
odoo_1      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo_1      |   File "/usr/local/lib/python3.11/site-packages/jinja2/filters.py", line 13, in <module>
odoo_1      |     from markupsafe import soft_unicode
odoo_1      | ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.11/site-packages/markupsafe/__init__.py)
```

Full docker compose output is attached for reference.
[docker-compose-log.txt](https://github.com/odoo/odoo/files/11052619/docker-compose-log.txt)
