### ISSUE TITLE
Glyphicons not available

### ISSUE THREAD

**Issue by PieterPaulussen** [odoo/odoo#12609]
Impacted versions: v9.0 & v9.0e

Steps to reproduce:
1. Open a runbot.
2. Edit website page
3. Insert code: `<a href="#"><span class="glyphicon glyphicon-star"></span> Star</a>`
4. Save page

Current behavior: The bootstrap icon is not displayed.

Expected behavior: The bootstrap icon should be displayed.

**Comment by Yenthe666** [comment]
@JKE-be could you give feedback on this? I've tested this too and they don't render correctly (404).

**Comment by PieterPaulussen** [comment]
My bad 👎

**Comment by Yenthe666** [comment]
@PieterPaulussen you might actually be right.
When adding an icon to an HTML page in a custom module the following console output is thrown up:
![image](https://cloud.githubusercontent.com/assets/6352350/16443547/c5faf0ea-3dd9-11e6-9224-abd6731d3ffd.png)
When you look at `/website/static/src/less/` there is no folder `fonts` and neither is the `.ttf` file.

**Comment by Yenthe666** [comment]
@Gorash this might be something for you too.

**Comment by JKE-be** [comment]
@Yenthe666 
It because Odoo use Font Awesome icon and not GlyphIcon.
Use fa fa-star and it will works !

**Comment by Yenthe666** [comment]
@JKE-be yeah I thought so, just wanted to make sure it was the case.
Alright too bad the Glyphicons aren't supported.

**Comment by lmignon** [comment]
@PieterPaulussen For one of my modules I've fixed the same issue by adding in `my_module/static/src/css` a new file named `bootstrap_font_fix.css` with the following content.
```css
@font-face {
  font-family: 'Glyphicons Halflings';

  src: url('/web/static/lib/bootstrap/fonts/glyphicons-halflings-regular.eot');
  src: url('/web/static/lib/bootstrap/fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('/web/static/lib/bootstrap/fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('/web/static/lib/bootstrap/fonts/glyphicons-halflings-regular.woff') format('woff'), url('/web/static/lib/bootstrap/fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('/web/static/lib/bootstrap/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```

This new file is loaded as usual for custom css
```xml
<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <data>
        <template id="assets_backend" name="my_module assets" inherit_id="web.assets_backend">
            <xpath expr="." position="inside">
                <link rel="stylesheet" href="/my_module/static/src/css/bootstrap_fonts_fixes.css"/>
            </xpath>
        </template>
    </data>
</odoo>
```
