### ISSUE TITLE
[16.0] Bad looking inline color widget

### ISSUE THREAD

**Issue by em230418** [odoo/odoo#130664]
Impacted versions: 16.0

Steps to reproduce:
Create a form with following arch:
```
<form>
  <field name="example_color_field" widget="color" nolabel="1" class="oe_inline"/>
</form>
```
Current behavior:

![Снимок экрана_2023-08-03_16-01-55](https://github.com/odoo/odoo/assets/52414052/0b7300aa-3b57-4fd0-a6fb-a72a387763b3)

Expected behavior:

![Снимок экрана_2023-08-03_16-01-12](https://github.com/odoo/odoo/assets/52414052/30738627-fe14-4ea0-bb33-4509a7b05dcc)

Suggested fix:
```diff
diff --git a/addons/web/static/src/views/form/form_controller.scss b/addons/web/static/src/views/form/form_controller.scss
index 7e245bf55b2..a1534f4db4a 100644
--- a/addons/web/static/src/views/form/form_controller.scss
+++ b/addons/web/static/src/views/form/form_controller.scss
@@ -87,7 +87,7 @@
     .oe_grey {
         opacity: 0.5;
     }
-    .oe_inline, .o_field_widget.oe_inline > * {
+    .oe_inline, .o_field_widget.oe_inline:not(.o_field_color) > * {
         width: auto!important;
     }
     .oe_left {
```

Workaround
```css
.o_field_widget.o_field_color.oe_inline > * {                                                        
    width: 30px !important;                                                                                                   
}
```

Ping @Polymorphe57 as author of https://github.com/odoo/odoo/commit/e67803f35e1cc7e6365b1871c457e3b232401d4f
