### ISSUE TITLE
Using --dev option does not change anythin

### ISSUE THREAD

**Issue by claudiostevanatocylix** [odoo/odoo#136050]
Impacted versions:
Odoo 14

Steps to reproduce:
Using docker, use command: --dev=xml
Try to change an xml file
Restart docker

Current behavior:
The view is not updated and it stays the same as before until I update manually the module

Expected behavior:
Loading view from xml instead of database

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by gdgellatly** [comment]
It works, on every single version with this command, in docker. I use it literally 12 hours a day on every version of Odoo from 13-16, community and enterprise. Every dev I know also uses it with docker.

**Comment by Agilis-Enterprise-Solutions** [comment]
I’m also experiencing the same issue with the following docker-compose.yml file:

```
version: '2'
services:
  web:
    command: --dev=xml
    image: odoo:15
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8015:8069"
    volumes:
      - data:/var/lib/odoo
      - /opt/odoo15ent/custom_addons/mobler:/etc/odoo
      - /opt/odoo15ent/addons:/mnt/extra-addons/addons
      - /opt/odoo15ent/custom_addons/mobler:/mnt/extra-addons/mobler
      - /opt/odoo15ent/custom_addons/odooapps:/mnt/extra-addons/odooapps
  postgres:
    image: postgres:latest
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data/pgdata

volumes:
  data:
  db:

```

**Comment by zhaqenl** [comment]
Good day, @gdgellatly!

I find that I’m also experiencing this with the following docker-compose.yml:

```
version: '2'
services:
  web:
    command: --dev=xml
    image: odoo:15
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8015:8069"
    volumes:
      - data:/var/lib/odoo
      - /opt/odoo15ent/custom_addons/mobler:/etc/odoo
      - /opt/odoo15ent/addons:/mnt/extra-addons/addons
      - /opt/odoo15ent/custom_addons/mobler:/mnt/extra-addons/mobler
      - /opt/odoo15ent/custom_addons/odooapps:/mnt/extra-addons/odooapps
  postgres:
    image: postgres:latest
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data/pgdata

volumes:
  data:
  db:
```

How do you have it set up so that after editing the XML files, we no longer need to manually re-upgrade the module? (Which in my workflow using Odoo with Docker, I have to re-run `docker-compose down` then `up` to restart, which should ideally not be done with `dev=all`, am I right?)

Tagging you, @claudiostevanatocylix.
