### ISSUE TITLE
Bootstrap 5 is incompatible with `wkhtmltopdf`

### ISSUE THREAD

**Issue by AaronBeaudoin** [odoo/odoo#136360]
### Steps to Reproduce

We are currently in the process of migrating from Odoo 13.0 to 16.0. After migrating our data and testing on Odoo 16.0, I've found that our reports do not show up correctly. After spending the better part of the day trying to locate the problem, I've narrowed it down to Bootstrap 5 using CSS variables that are incompatible with `wkhtmltopdf`.

In Bootstrap v4.3.1 we have the following code:

```css
body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5;
  color: #212529;
  text-align: left;
  background-color: #fff;
}
```

In Bootstrap v5.1.3 we have this instead:

```css
body {
  margin: 0;
  font-family: var(--bs-body-font-family);
  font-size: var(--bs-body-font-size);
  font-weight: var(--bs-body-font-weight);
  line-height: var(--bs-body-line-height);
  color: var(--bs-body-color);
  text-align: var(--bs-body-text-align);
  background-color: var(--bs-body-bg);
  -webkit-text-size-adjust: 100%;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
```

In my reports I'm experiencing spacing issues that appear to be due to incorrect line heights. I can "fix" the issue by adding a simple override after the Bootstrap CSS code like this, thereby reverting back to the Bootstrap 4 approach:

```
body {
  line-height: 1.5;
}
```

However, there are many other uses of CSS variables in Bootstrap 5 and I think this is likely to be the tip of the iceberg of the problem I'll be running into. The bottom line is that `wkhtmltopdf` hasn't been updated in forever and is literally a decade behind in terms of features.

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3253

### Impacted Versions

16.0

**Comment by AaronBeaudoin** [comment]
Another problem resulting from `wkhtmltopdf`'s lack of support for CSS custom properties (variables) is that Bootstrap 5's layout "gutter" implementation doesn't work for PDFs.

I had to apply the following "patch" to get my reports looking the same as in Odoo 13.0:

```css
.row {
  margin-left: -15px;
  margin-right: -15px;
}

.col-1, .col-2, .col-3, .col-4, .col-5, .col-6, .col-7,
.col-8, .col-9, .col-10, .col-11, .col-12, .col, .col-auto,
.col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7,
.col-sm-8, .col-sm-9, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm, .col-sm-auto,
.col-md-1, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7,
.col-md-8, .col-md-9, .col-md-10, .col-md-11, .col-md-12, .col-md, .col-md-auto,
.col-lg-1, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7,
.col-lg-8, .col-lg-9, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg, .col-lg-auto,
.col-xl-1, .col-xl-2, .col-xl-3, .col-xl-4, .col-xl-5, .col-xl-6, .col-xl-7,
.col-xl-8, .col-xl-9, .col-xl-10, .col-xl-11, .col-xl-12, .col-xl, .col-xl-auto {
  padding-left: 15px;
  padding-right: 15px;
}
```

I really think that this is a major oversight. I believe the following two things should happen:

- Add some sort of official "PDF-only" Bootstrap CSS styles "patch" to ensure proper rendering.
- Sooner rather than later, migrate to something other than `wkhtmltopdf`. The fact is, this really should happen at some point anyways since the package has not been maintained for quite some time. I am aware that there are not a lot of alternatives in this space, but regardless, we can't keep holding onto `wkhtmltopdf` forever.
