### ISSUE TITLE
[17.0] 413 REQUEST ENTITY TOO LARGE (not an nginx issue)

### ISSUE THREAD

**Issue by fractalf** [odoo/odoo#144144]
Before you all scream "set the `client_max_body_size` in your nginx!" bare with me.. because this is strange and not related to nginx/apache etc...

I'm running **only** odoo 17 and postgresql (in seperate docker containers).
Everything is working fine.

..but when uploading an old database file for 300+ MB I get 413 error from "some webserver" (odoo/werkzeug?)

This (curl command that uploads database file) is run **inside** the container running odoo:

```sh
root@48ccdd1ba908:/# curl -v -k -F 'master_pwd=ff' -F backup_file=@./db.zip -F 'copy=true' -F 'name=ff' http://localhost:8069/web/database/restore
*   Trying 127.0.0.1:8069...
* Connected to localhost (127.0.0.1) port 8069 (#0)
> POST /web/database/restore HTTP/1.1
> Host: localhost:8069
> User-Agent: curl/7.88.1
> Accept: */*
> Content-Length: 314811384
> Content-Type: multipart/form-data; boundary=------------------------06ec5e10120b3286
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
* HTTP 1.0, assume close after body
< HTTP/1.0 413 REQUEST ENTITY TOO LARGE
< Server: Werkzeug/2.2.2 Python/3.11.2
< Date: Wed, 29 Nov 2023 10:20:10 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 171
< Connection: close
< 
<!doctype html>
<html lang=en>
<title>413 Request Entity Too Large</title>
<h1>Request Entity Too Large</h1>
<p>The data value transmitted exceeds the capacity limit.</p>
* Closing connection 0
```

The webserver that makes this respone **must** be the odoo binary process, I cannot understand it to be anything else...

```sh
root@48ccdd1ba908:/# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
odoo           1  0.2  0.0 842672  1280 pts/0    Ssl+ 10:13   0:02 /usr/bin/python3 /usr/bin/odoo --dev all --db_host odoo17-db --db_port 5432 --db_user odoo 
odoo          40  0.0  0.0 842688  1996 pts/0    Sl+  10:13   0:00 /usr/bin/python3 /usr/bin/odoo --dev all --db_host odoo17-db --db_port 5432 --db_user odoo 
odoo          41  0.0  0.0 843712  3372 pts/0    Sl+  10:13   0:00 /usr/bin/python3 /usr/bin/odoo --dev all --db_host odoo17-db --db_port 5432 --db_user odoo 
odoo          43  0.0  0.0 842688  1988 pts/0    Sl+  10:13   0:00 /usr/bin/python3 /usr/bin/odoo --dev all --db_host odoo17-db --db_port 5432 --db_user odoo 
odoo          45  0.0  0.0 842688  1972 pts/0    Sl+  10:13   0:00 /usr/bin/python3 /usr/bin/odoo --dev all --db_host odoo17-db --db_port 5432 --db_user odoo 
odoo          47  0.0  0.0 845760  3348 pts/0    Sl+  10:13   0:00 /usr/bin/python3 /usr/bin/odoo --dev all --db_host odoo17-db --db_port 5432 --db_user odoo 
odoo          49  0.0  0.0 846784  3236 pts/0    Sl+  10:13   0:00 /usr/bin/python3 /usr/bin/odoo --dev all --db_host odoo17-db --db_port 5432 --db_user odoo 
odoo          50  0.0  0.0 842688  1972 pts/0    Sl+  10:13   0:00 /usr/bin/python3 /usr/bin/odoo --dev all --db_host odoo17-db --db_port 5432 --db_user odoo 
odoo          52  0.0  0.0 842688  2956 pts/0    Sl+  10:13   0:00 /usr/bin/python3 /usr/bin/odoo --dev all --db_host odoo17-db --db_port 5432 --db_user odoo 
odoo          54  0.0  0.0 842688  1984 pts/0    Sl+  10:13   0:00 /usr/bin/python3 /usr/bin/odoo --dev all --db_host odoo17-db --db_port 5432 --db_user odoo 
odoo          56  0.1  0.0 255760  3444 pts/0    S+   10:13   0:01 /usr/bin/python3 /usr/bin/odoo gevent --dev all --db_host odoo17-db --db_port 5432 --db_use
odoo          59  0.0  0.1 842688  8032 pts/0    SNl+ 10:13   0:00 /usr/bin/python3 /usr/bin/odoo --dev all --db_host odoo17-db --db_port 5432 --db_user odoo 
odoo          60  0.0  0.0 842688  7016 pts/0    SNl+ 10:13   0:00 /usr/bin/python3 /usr/bin/odoo --dev all --db_host odoo17-db --db_port 5432 --db_user odoo 
root          76  0.0  0.0   4188  1612 pts/1    Ss   10:19   0:00 /bin/bash
root         353  0.0  0.0   8100  4052 pts/1    R+   10:28   0:00 ps aux
```

### So, how do I increase this limit ?

I've done this for years and years in my old Odoo 12.0 setup, but this is now failing in the new Odoo 17.0 setup

I'm running version 17 in a docker container using the deb here:
https://download.odoo.com/17.0/nightly/deb/odoo_17.0.20231116_all.deb

**Comment by troykelly** [comment]
Experiencing the same issue with the Odoo supplied container.
As you have already pointed out (repeating here in the hope there are no "have you checked..." posts)

- This is not caused by an intermediary
- This is a response from the Odoo process itself

**Comment by troykelly** [comment]
The issue is caused by the line below. It is a hardcoded maximum that doesn't appear to be settable by anything other then a system parameter. This means it can't be (I don't know how to at least) set until you have created your instance - so anybody trying to restore a database larger than 128MiB is SOL.
https://github.com/odoo/odoo/blob/6e68fdd9595800a78166bacdfc26693a113fbb6d/odoo/http.py#L1500

**Comment by troykelly** [comment]
Anybody stuck on this using the default docker container can use the user and entrypoint override below. Odoo are typically very opinionated about anything in their code and do not take kindly to people suggesting something is wrong, so it's highly unlikely that this would ever change. Other ideas for a safer fix are welcome.

@fractalf I don't think this will be a solution for you - It seems like you are making your own containers?

Note: Don't just copy the below, I've provided a whole section so you can see `user` and `entrypoint` in context. You will need to implement for yourself.

```yaml
---
version: "3.8"
x-default-opts: &default-opts
  logging:
    driver: gelf
    options:
      gelf-address: ${GELF_SERVER}
      gelf-compression-type: none
      tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
      labels: purpose,site

# Define the default Odoo version at the service or compose level.
# This assumes that ODOO_MAJOR_VERSION is an environment variable defined outside of the file,
# or can be passed through Portainer or a `.env` file during deployment.
x-odoo-service: &odoo-service
  <<: *default-opts
  image: odoo:${ODOO_MAJOR_VERSION:-17}

services:
  odoo:
    <<: *odoo-service
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      - proxy
      - backend
    labels:
      - purpose=odoo
      - site=${SITE}
    deploy:
      replicas: ${ODOO_REPLICAS:-1}
      endpoint_mode: dnsrr
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role==worker
      update_config:
        parallelism: 2
        delay: 10s
      resources:
        limits:
          cpus: "6.00"
          memory: 4G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.constraint-label=traefik-public
        #----------------------------------------------- routers for: odoo --------------------------------------------------
        # http
        - traefik.http.routers.${SITE}-http.rule=(Host(`${DOMAIN}`, `www.${DOMAIN}`))
        - traefik.http.routers.${SITE}-http.entrypoints=http
        - traefik.http.routers.${SITE}-http.middlewares=servicests,block-apple,https-redirect,reporturi
        - traefik.http.routers.${SITE}-http.service=${SITE}
        # https
        - traefik.http.routers.${SITE}-https.rule=(Host(`${DOMAIN}`, `www.${DOMAIN}`))
        - traefik.http.routers.${SITE}-https.entrypoints=http3
        - traefik.http.routers.${SITE}-https.service=${SITE}
        - traefik.http.routers.${SITE}-https.tls.certresolver=${SITE_RESOLVER}
        - traefik.http.routers.${SITE}-https.middlewares=gzip,limit,reporturi,block-apple
        #----------------------------- routes for: odoo/web/database || odoo/website/info  -----------------------------
        # http
        - traefik.http.routers.${SITE}-db-http.rule=(Host(`${DOMAIN}`, `www.${DOMAIN}`)) && (PathPrefix(`/web/database`) || PathPrefix(`/website/info`))
        - traefik.http.routers.${SITE}-db-http.entrypoints=http
        - traefik.http.routers.${SITE}-db-http.service=${SITE}
        - traefik.http.routers.${SITE}-db-http.middlewares=servicests,block-apple,https-redirect,reporturi
        - traefik.http.services.${SITE}-db-http.loadbalancer.server.port=8069
        # https
        - traefik.http.routers.${SITE}-db-https.rule=(Host(`${DOMAIN}`, `www.${DOMAIN}`)) && (PathPrefix(`/web/database`) || PathPrefix(`/website/info`))
        - traefik.http.routers.${SITE}-db-https.entrypoints=http3
        - traefik.http.routers.${SITE}-db-https.service=${SITE}
        - traefik.http.routers.${SITE}-db-https.tls.certresolver=${SITE_RESOLVER}
        - traefik.http.routers.${SITE}-db-https.middlewares=gzip,limit,reporturi,block-apple
        - traefik.http.services.${SITE}-db-https.loadbalancer.server.port=8069
        #====================================================== services ===========================================================
        - traefik.http.services.${SITE}.loadbalancer.server.port=8069
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - config:/etc/odoo
      - sessions:/var/lib/odoo/sessions
      - filestore:/var/lib/odoo/filestore
      - addons:/var/lib/odoo/addons
      - extra-addons:/mnt/extra-addons
      - type: tmpfs
        target: "/tmp"
        tmpfs:
          size: 1610612736
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    command:
      [
        "--proxy-mode",
        "--workers",
        "4",
        "--max-cron-threads",
        "${ODOO_SITE_CRON_THREADS:-0}",
        "--log-level",
        "debug_rpc_answer",
        "--log-web",
        "--smtp",
        "${SMTP_HOST}",
        "--smtp-port",
        "${SMTP_PORT}",
        "--smtp-ssl",
        "--smtp-user",
        "${SMTP_USER}",
        "--smtp-password",
        "${SMTP_PASSWORD}",
        "--data-dir",
        "/var/lib/odoo",
        "--addons-path",
        "/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons",
      ]
    user: root
    entrypoint: >
      /bin/bash -c 
      'if ! command -v gosu &> /dev/null; then
         apt-get update && apt-get install -y gosu;
       fi;
       if [ ! -f /etc/odoo/odoo.conf ]; then
         echo "[options]" > /etc/odoo/odoo.conf;
       elif ! grep -q "^\[options\]" /etc/odoo/odoo.conf; then
         sed -i "1i [options]" /etc/odoo/odoo.conf;
       fi;
       if ! grep -q "^web.max_file_upload_size" /etc/odoo/odoo.conf; then
         echo "web.max_file_upload_size = ${ODOO_MAX_FILE_UPLOAD_SIZE:-134217728}" >> /etc/odoo/odoo.conf;
       else
         sed -i "/^\[options\]/,/^\[/!b;/^web.max_file_upload_size/cweb.max_file_upload_size = ${ODOO_MAX_FILE_UPLOAD_SIZE:-134217728}" /etc/odoo/odoo.conf;
       fi;
       chown odoo: /etc/odoo/odoo.conf;
       if [ -f /usr/lib/python3/dist-packages/odoo/http.py ]; then
         sed -i "s/^DEFAULT_MAX_CONTENT_LENGTH.*/DEFAULT_MAX_CONTENT_LENGTH = ${ODOO_MAX_FILE_UPLOAD_SIZE:-134217728} # Changed by docker compose entry override/" /usr/lib/python3/dist-packages/odoo/http.py;
       fi;
       exec gosu odoo /entrypoint.sh $$@'
    healthcheck:
      test: ["CMD-SHELL", "curl -X HEAD -I http://127.0.0.1:8069"]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=${POSTGRES_PASSWORD}
      - ODOO_MAX_FILE_UPLOAD_SIZE=${ODOO_MAX_FILE_UPLOAD_SIZE:-134217728}
```
