### ISSUE TITLE
Scheduled tasks not running

### ISSUE THREAD

**Issue by rossigee** [odoo/odoo#23002]
Impacted versions:

11 (and all previous versions)

Steps to reproduce:

Run up a simple docker stack locally using latest docker image:

```
version: '3'

services:
  web:
    image: odoo:latest
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
```

...

```
docker-compose up
```

Go to http://localhost:8069/web?debug.

Create a 'test1' database, including demo data, and log in. Switch to developer/debug mode.

Go to Settings > Apps > Scheduled Actions.

Edit the default 'autovacuum' task. Reschedule to run every minute. Save.

Wait a few minutes. Watch the docker 'app' container logs to see if cron job is being running.

Current behavior:

No further log entries seen in the log.

Expected behavior:

A log entry every minute showing the cron job thread running, as scheduled.

(seems to be the same problem as was reported in #3746)
