### ISSUE TITLE
[10.0] project_issue install error: it's trying to install demo data when said --without-demo

### ISSUE THREAD

**Issue by miqmago** [odoo/odoo#23908]
Impacted versions: 10.0-20171030 (Community Edition)

Steps to reproduce: install project_issue in a dockerized odoo, in a database without demo data (trying to install it via application panel gives the same error, checkbox demo data unchecked)

```sh
docker-compose -f docker-compose.yml up
```

docker-compose.yml:
```yml
version: '2'
services:
  web:
    image: odoo:10.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - /var/www/odoo-common/addons:/mnt/extra-addons
    command: -d bg -i project_issue --without-demo WITHOUT_DEMO
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
```

Current behavior:
```
mar 27 17:10:05 servidor-1 docker-compose[10338]: db_1   | ERROR:  null value in column "name" violates not-null constraint
mar 27 17:10:05 servidor-1 docker-compose[10338]: db_1   | DETAIL:  Failing row contains (15, null, 2018-03-27 17:10:03.838053, 1, null, 1, null, 1, 2018-03-27 17:10:03.838053, t, null, t, f).
mar 27 17:10:05 servidor-1 docker-compose[10338]: db_1   | STATEMENT:  INSERT INTO "account_analytic_account" ("id", "active", "use_tasks", "company_id", "use_issues", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('account_analytic_account_id_seq'), true, true, 1, false, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  | 2018-03-27 17:10:05,675 1 INFO bg odoo.sql_db: bad query: INSERT INTO "account_analytic_account" ("id", "active", "use_tasks", "company_id", "use_issues", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('account_analytic_account_id_seq'), true, true, 1, false, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  | 2018-03-27 17:10:05,680 1 ERROR bg odoo.modules.registry: Failed to load registry
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  | Traceback (most recent call last):
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 82, in new
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 339, in load_modules
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     loaded_modules, update_module)
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 237, in load_marked_modules
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 159, in load_module_graph
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     _load_data(cr, module_name, idref, mode, kind='demo')
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 95, in _load_data
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 845, in convert_file
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 915, in convert_xml_import
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     obj.parse(doc.getroot(), mode=mode)
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 799, in parse
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     self._tags[rec.tag](rec, de, mode=mode)
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 707, in _tag_record
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1229, in _update
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     record = record.create(values)
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/mnt/extra-addons/odoo_sale_order_project_tasks/models/sale.py", line 43, in create
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     new_project = super(Project, self).create(vals)
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/addons/project/models/project.py", line 254, in create
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     return super(Project, self).create(vals)
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_alias.py", line 223, in create
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     )).create(vals)
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_thread.py", line 228, in create
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     thread = super(MailThread, self).create(values)
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3826, in create
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     record = self.browse(self._create(old_vals))
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3887, in _create
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     parent_id = self.env[parent_model].create(parent_vals).id
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/addons/project/models/project.py", line 704, in create
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     analytic_account = super(AccountAnalyticAccount, self).create(vals)
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_thread.py", line 228, in create
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     thread = super(MailThread, self).create(values)
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3826, in create
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     record = self.browse(self._create(old_vals))
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3921, in _create
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 154, in wrapper
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     return f(self, *args, **kwargs)
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 231, in execute
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |     res = self._obj.execute(query, params)
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  | ParseError: "null value in column "name" violates not-null constraint
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  | DETAIL:  Failing row contains (15, null, 2018-03-27 17:10:03.838053, 1, null, 1, null, 1, 2018-03-27 17:10:03.838053, t, null, t, f).
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  | " while parsing /usr/lib/python2.7/dist-packages/odoo/addons/project_issue/data/project_issue_demo.xml:3, near
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  | <record id="project.project_project_1" model="project.project">
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |             <field name="use_issues" eval="True"/>
mar 27 17:10:05 servidor-1 docker-compose[10338]: web_1  |         </record>
```

Expected behavior: no error

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I think the syntax of the command should be `--without-demo=all`

**Comment by miqmago** [comment]
same error, tried also `--without-demo=all`, `--without-demo all`, `--without-demo=WITHOUT_DEMO`

Also from applications panel the error is the same

**Comment by pedrobaeza** [comment]
This is something with your deployment method, as the option is working on my side. Please check that you don't have mark in your DB some entries in table ir_module_module with demo=True.

**Comment by miqmago** [comment]
That is quite strange... The first time I've installed this database I used this command:

```yml
version: '2'
services:
  web:
    image: odoo:10.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - /var/www/odoo-common/addons:/mnt/extra-addons
    command: -d bg -i crm,project,stock,sale,stock_account,hr_timesheet,mail,hr_holidays,account,account_asset,account_accountant,hr_payroll,website,purchase,hr,hr_recruitment,account_bank_statement_import,account_budget,analytic,auth_oauth,auth_signup,barcodes,base_action_rule,base_geolocalize,base_iban,base_setup,base_vat,bus,contacts,decimal_precision,document,fetchmail,google_account,google_calendar,hr_contract,hr_recruitment_survey,l10n_es,link_tracker,mail_tracking,odoo_sale_order_project_tasks,odoo_sales_order_partial_invoice,payment,payment_paypal,payment_transfer,portal,portal_sale,portal_stock,procurement,procurement_jit,product,project_timeline,rating,report,resource,sale_crm,sales_team,sale_stock,sale_timesheet,stock_dropshipping,survey_crm,utm,website_crm,website_crm_partner_assign,website_customer,website_form,website_google_map,website_hr,website_hr_recruitment,website_links,website_livechat,website_mail,website_mass_mailing,website_partner,website_payment,website_portal,website_portal_sale,website_project,website_project_timesheet,website_theme_install,web_timeline,survey,mass_mailing,maintenance,calendar,website_blog,im_livechat --without-demo WITHOUT_DEMO
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
```

But I've just selected form the table wit demo=True:

![captura de pantalla 2018-03-27 a les 19 57 17](https://user-images.githubusercontent.com/1849488/37985551-520235ca-31f9-11e8-925d-832903e083c3.png)

Amazing: updated the table and all worked!! Many thanks!!

```sql
UPDATE public.ir_module_module SET demo=False where demo=True;
```
