### ISSUE TITLE
[12.0] Docker image does not load add-ons

### ISSUE THREAD

**Issue by wtrz** [odoo/odoo#28295]
**Impacted versions:**
12.0 using docker
**Steps to reproduce:**
using docker. 

```
version: '2'
services:
  web:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
```
have addon files placed in ./addons
i.e. muk_account_bank_statement_import_sheet, muk_account_accountant. 

in terminal:
`sudo docker-compose up -d
`
navigate via browser in developer mode to APPS\Update Apps list
(http://localhost:8069/web/?debug#menu_id=48&action=36)

click ' update' 

**Current behavior:**
short loading screen. Removed apps filter.  modules do not become available 

**Expected behavior:**
new addons should load and become available.
