### ISSUE TITLE
QWeb report not translated

### ISSUE THREAD

**Issue by sabba** [odoo/odoo#35553]
Hello, 
I'm having troubles trying to generate a translated custom report.

So, I tried to test the translation framework on a standard module and I'm not able to generate translated PDF/HTML.

I have used the purchase module as explained below.
Where I'm wrong?

I have also tried on this demo instance without success: https://demo3.odoo.com/

Thank you!

---

Impacted versions:
Odoo 12.0-20190424 - latest docker image (ID: cd4d666c0dc5)

Steps to reproduce:

- New Database installation NOT in english. In my test "Italian"
- Installation of Purchase module
- Check admin user has languange set into preferences (my test "Italian")
- Create a new RFQ/Order
- Print PDF Order (or access to /report/html/purchase.report_purchaseorder/1)

Current behavior:

- Report NOT translated (pdf and html)

Expected behavior:

- Report translated according to translated terms that seems to be correctly loaded

Video/Screenshot link (optional):

---
**Installed Languages**
![image](https://user-images.githubusercontent.com/946347/62691422-f23d0e80-b9ce-11e9-9d91-831854d9eb0f.png)

---
**User Preferences**
![image](https://user-images.githubusercontent.com/946347/62691492-1567be00-b9cf-11e9-9ff5-71f128b84005.png)

---
**Translated Terms**
![image](https://user-images.githubusercontent.com/946347/62691538-2dd7d880-b9cf-11e9-8791-72a49a0d8d8b.png)

---
**Example of RFQ**
![image](https://user-images.githubusercontent.com/946347/62691584-4516c600-b9cf-11e9-9684-20a2d57690c4.png)

---
**PDF output**
![image](https://user-images.githubusercontent.com/946347/62691614-552ea580-b9cf-11e9-986d-0bf22a35723b.png)

---
**HTML output**
![image](https://user-images.githubusercontent.com/946347/62691639-624b9480-b9cf-11e9-855c-833b7110854c.png)

**Comment by pedrobaeza** [comment]
RfQ / Purchase order is translated in the language of the supplier, so that's something expected. Change the language of your supplier and try again.

Closing meanwhile and this is working correctly in my side.

**Comment by sabba** [comment]
Hello @pedrobaeza 
Thank you for the answer.

You are right, RFQ/Purchase Order is translated in the language of the supplier.

![image](https://user-images.githubusercontent.com/946347/62710498-b9fdf600-b9f7-11e9-910c-e48e31f90cba.png)

I'm sorry for the error into the description, but the translation does not work anyway. :(

As I described before I have created a DB with only **one language** installed . Whereby in my example the supplier language was the only one available (Italian), as you can see in this screen

![image](https://user-images.githubusercontent.com/946347/62710366-74412d80-b9f7-11e9-9a02-d02c20cf177b.png)

But my instance continues to generate english report (obviously I'm trying on a fresh new installation with the only purchase module installed).

Am I losing something or is a problem of the dockerized instance I'm using?
Thank you again!

**Comment by pedrobaeza** [comment]
Have you loaded translations from *Settings > Translation > Load a translation*?

**Comment by sabba** [comment]
Yes, many times. With and without overwriting terms.

As you can see in one of the screenshot i put in my first message, the strange thing is that terms seem to be correctly translated and loaded into the DB, but simply not applied during template rendering. :(

![image](https://user-images.githubusercontent.com/946347/62691538-2dd7d880-b9cf-11e9-8791-72a49a0d8d8b.png)

**Comment by pedrobaeza** [comment]
OK, let's reopen this and this is not possible to try on runbot as it creates directly DBs on English.

@mart-e have you observed this problem?

**Comment by mart-e** [comment]
> this is not possible to try on runbot as it creates directly DBs on English

You can achieve the same by loading Italian, switching all users to Italian and deactivating English language

Your issue is quite odd, I just tried and had no issue.
One way to get that is if you set no language on the supplier. Setting no language means using the "raw" values in the database, hence English (but it does not seem to be the case here cf your screenshot).

**Comment by sabba** [comment]
If useful, this is my full odoo.conf

```
[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = admin
load_language = en_US
lang = en_US
csv_internal_sep = ,
db_maxconn = 64
db_name = backend
db_template = template1
dbfilter = .*
debug_mode = True
auto_reload = True
email_from = False
without_demo = all
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 60
limit_time_real = 120
list_db = True
log_db = False
log_handler = [':DEBUG']
log_level = debug
logfile = None
longpolling_port = 8072
max_cron_threads = 1
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
workers = 0
xmlrpc = True
xmlrpc_interface =
xmlrpc_port = 8069
xmlrpcs = True
xmlrpcs_interface =
xmlrpcs_port = 8071
proxy_mode = False
```

And this is my docker-compose.yml file

```
version: '3'
services:
  odoo:
    image: odoo:12.0
    networks:
      - administrative
    depends_on:
      - odoodb
    ports:
      - "8069:8069"
    command: ["odoo", "-d", "backend", "--dev=all"]
    stdin_open: true
    tty: true
    environment:
      - HOST=odoodb
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./conf/odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/extra-addons
  odoodb:
    image: postgres:11
    networks:
      - administrative
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    stop_grace_period : 120s
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
networks:
  administrative:
```
