### ISSUE TITLE
[ALL] Blank odoo page if language != English (dockerized)

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#37959]
### Impacted versions:
All
### Steps to reproduce:
Install Odoo with the official Docker steps:
```yaml
version: '2'
services:
  web:
    image: odoo:12.0
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo
  mydb:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
```

Create a database in Spanish (or any other language)

### Current behavior:
Blank odoo page after login in, with no error message or weird logs.

### Expected behavior:
Successful login just as it happens when installing English.

#### Note
This is not a **standard behavior** it seems to depend on the host where Docker resides, but I've been wandering for days without no clues on why the Host should affects Odoo's behavior inside the container, and just when the language is different than English.

Got a report of this happening in WSL (Windows Subsystem) and I could successfully reproduce it.

Might be related:
https://github.com/odoo/odoo/issues/22463
https://github.com/odoo/odoo/issues/19627
