### ISSUE TITLE
Odoo Website Client Error on Firefox

### ISSUE THREAD

**Issue by korakotlee** [odoo/odoo#47129]
Impacted versions: Odoo 13.0

Steps to reproduce:
- Install Website App
- hover on the upper left menu

Current behavior:

When I hover on the upper left menu; this error happen only in Firefox 73
If I clear browser cookie and cache; it's gone but then comes back.
On Chrome it works fine.

Error:

Traceback:
exception@http://localhost:8069/web/content/522-70a98a4/1/web.assets_common_lazy.js:3593:7
_render@http://localhost:8069/web/content/522-70a98a4/1/web.assets_common_lazy.js:3638:103
render@http://localhost:8069/web/content/522-70a98a4/1/web.assets_common_lazy.js:3634:151
_onOeApplicationsHovered/<@http://localhost:8069/web/content/523-2da2123/1/web.assets_frontend_lazy.js:158:288
Expected behavior:

Video/Screenshot link (optional):
![](https://raw.githubusercontent.com/korakotlee/img/master/odoo/odoo_firefox.png)

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by ivanporras** [comment]
@korakotlee  Could you try reboot your service?

**Comment by korakotlee** [comment]
I rebooted my machine still have problem.
I tested the runbot for branch 13.0, it works fine on Firefox, will keep trying.
However I found error the following error in the developer tool console:

`Error: QWeb2: Template 'website.oe_applications_menu' not found`

**Comment by korakotlee** [comment]
After a few days, it works now. I think the cache expire and regenerate a new js pack, Thanks.

**Comment by rb3606** [comment]
I have reproduced same behaviour with fresh odoo13 installation. Only elearning installed.

![image](https://user-images.githubusercontent.com/6355966/78643821-7e8f3080-78d2-11ea-9708-f961393a1c95.png)

**Comment by anthonygrant** [comment]
I get the same error using chrome or firefox. I'm using the latest docker image. Version 12 works fine. Version 13 has this error.
It is super easy to reproduce by following these steps.
1. Use this docker-compose.yml file
```yaml
version: '2'
services:
  web:
    image: odoo:13
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
```

1. Run `docker-compose up`

1. In Chrome go to `localhost:8069`

1. Enter the database settings to create a new database
![image](https://user-images.githubusercontent.com/2901666/89863735-0ae99100-dbee-11ea-9bed-dc374d293b0d.png)

1. Add the app `eCommerce`

1. Select the `Default` theme

Now when you mouse over the Website menu option in the top left corner you will get this error. Guaranteed, everytime.

![image](https://user-images.githubusercontent.com/2901666/89863373-4e8fcb00-dbed-11ea-9e0b-4cfe0f5281ec.png)

**Comment by Jzano** [comment]
Hi, I get the same error using chrome or firefox (Odoo V14 CE). I'm using the latest docker image. 

```
version: '2'
services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
```
