### ISSUE TITLE
cannot import name 'cloc' from 'odoo.tools' (/usr/lib/python3/dist-packages/odoo/tools/__init__.py) - - -

### ISSUE THREAD

**Issue by nrome-n** [odoo/odoo#53771]
Impacted versions:
odoo 13 docker
Steps to reproduce:
instating odoo docker with odoo enterprise module

```
version: '2'
services:
  db:
    image: 'postgres:11'
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - './postgresql:/var/lib/postgresql/data'
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - '5555:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - './pgadmin:/var/lib/pgadmin'
  odoo13:
    image: 'odoo:13'
    depends_on:
      - db
    ports:
      - '10013:8069'
    tty: true
    command: '-- --dev=reload'
    
    volumes:
      - './addons:/mnt/extra-addons'
      - './enterprise:/mnt/enterprise-addons'
      - './config:/etc/odoo'
    restart: always
```

Current behavior:
```
ImportError: cannot import name 'cloc' from 'odoo.tools' (/usr/lib/python3/dist-packages/odoo/tools/__init__.py)
```

Expected behavior:
Be able to user odoo and create new odoo db

Video/Screenshot link (optional):
