### ISSUE TITLE
Error in Website App on hover over website menu and edit menu

### ISSUE THREAD

**Issue by anthonygrant** [odoo/odoo#55715]
Impacted versions: 13

I get this error using chrome or firefox. I'm using the latest docker image. Version 12 works fine. Version 13 has this error.
It is super easy to reproduce by following these steps.

1. Use this docker-compose.yml file
```yaml
version: '2'
services:
  web:
    image: odoo:13
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
```

1. Run `docker-compose up`

1. In Chrome go to `localhost:8069`

1. Enter the database settings to create a new database
![image](https://user-images.githubusercontent.com/2901666/89863735-0ae99100-dbee-11ea-9bed-dc374d293b0d.png)

1. Add the app `website`

1. Select the `Default` theme (doesn't matter which theme. Happens on any)

Now when you mouse over the Website menu option in the top left corner you will get this error. Guaranteed, everytime.

![image](https://user-images.githubusercontent.com/2901666/89863373-4e8fcb00-dbed-11ea-9e0b-4cfe0f5281ec.png)
