### ISSUE TITLE
Settings Missing in odoo 13 from docker hub image

### ISSUE THREAD

**Issue by alderson59** [odoo/odoo#58080]
Impacted versions:
13

Steps to reproduce:
Fresh install.
Run docker compose using the following file, with clean volumes
```
version: '2'
services:
  web:
    image: odoo:13.0
    depends_on:
      - db
    user: 1000:1000
    ports:
      - "8069:8069"
    environment:
      - PASSWORD=1234
    volumes:
      - /path1:/var/lib/odoo
      - /path2:/etc/odoo
      - /path3:/mnt/extra-addons
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /path4:/var/lib/postgresql/data/pgdata
```
Go to x.x.x.x:8069
Set up as usual
Click on the four-square icon on top left
Click on Settings

Current behavior:
Clicking on Settings does not bring up Settings page, but instead brings up User page.
Clicking on Settings any further does not do anything.
There are no Settings or Dashboard tabs available at the top menu.

Expected behavior:
Settings page should be shown, with Dashboard and Settings tabs available, just like in odoo 12

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/69715968/93687298-4f225800-faef-11ea-965e-879b1cf39b19.png)
![image](https://user-images.githubusercontent.com/69715968/93687303-56496600-faef-11ea-9b0a-3cb2281be68e.png)
