### ISSUE TITLE
[14.0] cannot activate developer mode with enterprise modules: TypeError: self.update_debug_manager is not a function

### ISSUE THREAD

**Issue by tom-m-26h** [odoo/odoo#61623]
Impacted versions:
14.0-20201026

Steps to reproduce:
1. launch Community Edition using odoo:14 docker image
2. create database "odoo14"
3. login
4. click Apps, install "base_setup" (to be able to enter Settings)
5. Settings
6. Activate Developer Mode, open Apps, observe that everything works as expected
7. logout
8. download enterprise modules from https://codeload.github.com/odoo/enterprise/zip/14.0
9. unzip enterprise modules into /mnt/enterprise in the docker container
10. append ",/mnt/enterprise" to addons_path in /etc/odoo/odoo.conf
11. in a shell in the container run: `/usr/bin/python3 /usr/bin/odoo --db_host db --db_port 5432 --db_user odoo --db_password password --database odoo14 --init web_enterprise --stop-after-init`
12. in the shell start odoo: `/usr/bin/python3 /usr/bin/odoo --db_host db --db_port 5432 --db_user odoo --db_password password`
13. login and observe: developer mode is active as indicated by the username+dbname string `Administrator (odoo14)` at the upper right-hand corner
14. click Apps

Current behavior:
Apps not opened, `Odoo Client Error` is displayed instead.
Any further action leads to the same error, nothing works.
The only option is to click the "bug" icon and select "leave developer mode" - everything seems to work again after that.

Error details:

```
Error:
Traceback:
TypeError: self.update_debug_manager is not a function
    at Class.self.toggleHomeMenu (http://dev-app01.26house.com:8074/web/content/46-19a936f/web.assets_backend.js:3515:6)
    at Class.current_action_updated (http://dev-app01.26house.com:8074/web/content/46-19a936f/web.assets_backend.js:508:246)
    at Class.prototype.<computed> (http://dev-app01.26house.com:8074/web/content/45-f8e5256/web.assets_common.js:4616:488)
    at Class.current_action_updated (http://dev-app01.26house.com:8074/web/content/46-19a936f/web.assets_backend.js:643:322)
    at Class.current_action_updated (http://dev-app01.26house.com:8074/web/content/45-f8e5256/web.assets_common.js:4619:371)
    at Class.current_action_updated (http://dev-app01.26house.com:8074/web/content/46-19a936f/web.assets_backend.js:486:1043)
    at Class.<anonymous> (http://dev-app01.26house.com:8074/web/content/45-f8e5256/web.assets_common.js:4752:11)
    at Class.trigger (http://dev-app01.26house.com:8074/web/content/45-f8e5256/web.assets_common.js:4750:180)
    at Class._trigger_up (http://dev-app01.26house.com:8074/web/content/45-f8e5256/web.assets_common.js:4756:378)
    at Class._trigger_up (http://dev-app01.26house.com:8074/web/content/45-f8e5256/web.assets_common.js:4756:462)
```

Expected behavior:

The "Apps" app working normally + developer mode active. No error messages.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

You should take care that the enterprise code can't be disclosed.

**Comment by tom-m-26h** [comment]
@pedrobaeza , would you mind to elaborate on the instllation instructions? I started from the CE version based on the official odoo:14 docker image. Then followed the steps in [From Community to Enterprise / On Linux, using the source code](https://www.odoo.com/documentation/14.0/setup/enterprise.html#on-linux-using-the-source-code), but still got the error.

I attach my docker-compose.yml (private info redacted):
```
version: '2'
services:
  web:
    image: odoo:14.0
    # image: 56d3e3d980e7
    depends_on:
      - db
    ports:
      - "9999:8069"
    volumes:
      # filestore:
      - odoo-web-data:/var/lib/odoo
      # enterprise modules
      - ./enterprise/:/mnt/enterprise
      # config
      - ./config/:/etc/odoo
      # local addons
      - ./addons/:/mnt/addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
```
And the corresponding Dockerfile:
```
FROM odoo:14.0

ENV PATH /usr/bin/:$PATH

CMD ["sleep", "360000"]
```
Plus the commands executed in the container:

1. docker-compose up
2. create db, login, activate developer mode, logout
3. docker-compose down
4. download and copy the enterprise modules into ./enterprise
4. docker build .
5. modify docker-compose.yml to use the new image - change "image: odoo:14.0" to "image: 56d3e3d980e7"
6. docker-compose up --detach
7. docker exec --tty --interactive odoo14debug_web_1 bash
8. run:
8.1 /usr/bin/python3 /usr/bin/odoo --db_host db --db_port 5432 --db_user odoo --db_password odoo --database odoo14 --init web_enterprise --stop-after-init
8.2 /usr/bin/python3 /usr/bin/odoo --db_host db --db_port 5432 --db_user odoo --db_password odoo
9. login
10. geting the error




Please note that we would prefer not to do the installation from a deb package if it does not allow to "git pull" new revisions of the CE code instantly during our development process. But the install documentation you mentioned does not deal with this. We - as a silver odoo partner - do have access to the EE repository and want to git pull from that too.
