### ISSUE TITLE
[Docker][odoo-13ce] Missing folder: locale of library pdfjs in docker image

### ISSUE THREAD

**Issue by NothingCtrl** [odoo/odoo#61923]
**Impacted versions**: Odoo 13ce

**Steps to reproduce:**

Create an image from odoo 13 [docker-hub](https://hub.docker.com/_/odoo?tab=description), example `docker-compose.yaml`
```yaml
version: '2'
services:
  web:
    image: odoo:13.0
    depends_on:
      - db
    ports:
      - "9099:8069"
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
```

**Current behavior:**

These is no folder `/usr/lib/python3/dist-packages/odoo/addons/web/static/lib/pdfjs/web/locale`
Error 404 when view a pdf attachment in web view.

**Expected behavior:**

This folder and it's file should exist.

**Video/Screenshot link (optional):**
![picture059-3](https://user-images.githubusercontent.com/5380820/99519101-ffafb980-29c3-11eb-86d6-1950a08bb6de.png)
