### ISSUE TITLE
Enlarge the select2 dropdown to make the import readable and usable

### ISSUE THREAD

**Issue by WoLpH** [odoo/odoo#65019]
Impacted versions:

Tested with CE 12, 13 and 14

Steps to reproduce:

Go to any import and use the dropdown (see screenshots below)

Current behavior:

A very long list with several hard to read items because they are wrapped.

Expected behavior:

A slightly wider (and perhaps higher) list which is easier to read.

Video/Screenshot link (optional):

The current state:

![image](https://user-images.githubusercontent.com/270571/105734768-4b865e00-5f33-11eb-9a0a-1cd1f5d081ed.png)

After applying a bit of user-css as a workaround:

![image](https://user-images.githubusercontent.com/270571/105734954-75d81b80-5f33-11eb-87d8-e0530cec4207.png)

The user-css used through Stylus (although I would suggest editing the select2 parameters instead):
```css
    div.oe-import_selector,
    #select2-drop {
        width: 500px !important;
        height: 70vh;
    }
    .select2-results {
        max-height: 100vh !important;
        height: calc(100% - 35px);
    }
```
