### ISSUE TITLE
Yaml create record with uid=1 instead of uid given by context

### ISSUE THREAD

**Issue by damdam-s** [odoo/odoo#8107]
If you set the user for a yaml test, it will not be used for create methods (admin is used instead).
Seen in v8.

Example : crm.lead creation. Put pdb in create method of `crm.lead` object.
Then, run this yaml :

``` yaml
!python {model: crm.lead}: |
    lead = model.create(cr, uid, {'name': 'TTTT', "section_id": ref('sales_team.crm_case_section_1')}, context=context)
```

In the debugger, if you print arguments of create method, you will see `uid = XX` (XX = user_id running yaml import.

---

If you run this yaml import :

``` yaml
!record {model: crm.lead, id: lead_1}:
    name: "Sell something"
    section_id: sales_team.crm_case_section_1
```

In the debugger, you will see `uid=1`.

I think the 2 statements should have the same behaviour concerning the uid used to create a record.
Thanks
