### ISSUE TITLE
website: overlapping fixed header

### ISSUE THREAD

**Issue by chienandalu** [odoo/odoo#88195]
*Impacted versions:* all

*Steps to reproduce:*

- Configure an achor to an element in the middle of a large page.
- Go to the relative anchor from a link within the page or directly (#whatever-id-you-set-before)

*Current behavior:*

The top of the anchored block is hidden by the fixed header

*Expected behavior:*

The scroll respects the space of the anchor.

A possible solution would be this css fix:
```scss
// Ref: https://css-tricks.com/fixed-headers-on-page-links-and-overlapping-content-oh-my/
// Support: https://caniuse.com/?search=scroll-padding-top
html {
  scroll-padding-top: $top-menu-bar-height;
}
```

Video/Screenshot link (optional):

![fixed-header-overlapping](https://user-images.githubusercontent.com/5040182/162152371-549ca60a-8ad4-4998-a70b-82af5a758b9d.gif)
